### ISSUE TITLE
Is cs-studio.target valid?

### ISSUE THREAD

**Issue by willrogers** [ControlSystemStudio/org.csstudio.product#11]
At https://github.com/ControlSystemStudio/org.csstudio.product/tree/633e51d61f0c57f9d9723bb556566e6f57bc642b there seem to have been `cs-studio.target` and `repository/cs-studio.target`.

In https://github.com/ControlSystemStudio/org.csstudio.product/commit/e6b0af0634d13aaf811159812f843061211155ab Kay removed `repository/cs-studio.target`, but `cs-studio.target` remains.  It seems to be out of date.  

Should it also be removed?

**Comment by kasemir** [comment]
The target to use should be the one in the cs-studio repo, build/target-files/target-dev.target

.. except last time I tried, it would not work as is. I had to 'update', and always ended up with slightly different versions for several of the plugins.

So it would have to be updated to get back to one that everybody can use "as is".
.. except we should also move to Eclipse 4.5 on master, so the target would then need to point to Eclipse 4.5 as well.

Still, problems with the "one" target still mean we should have that one target and not additional targets like the one the o.c.product repo.

**Comment by shroffk** [comment]
Yes, this should be removed... all target definition files should be kept in the target-file project.

We do need to fine tune our target definitions to point to update sites and features that persist..otherwise we are stuck with this issue of updating. 

For mars the current target-dev will be moved to target-4.1 and the new dev should point to the eclipse 4.5 update sites.

The purpose for the target in the product and the template.product repos is so that people can use the target files and set up the eclipse IDE without having to clone the main cs-studio repo.

**Comment by willrogers** [comment]
Well, this one is out of date anyway.

**Comment by shroffk** [comment]
@willrogers can I close this Issue?

**Comment by willrogers** [comment]
Yes.  I don't really use the target definition files, but the one I mentioned was out of date.
